#!/bin/sh
set -e

# Copyright (C) 2016-2019 Bibliotheca Alexandrina
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

subdir="$(readlink -f "$0").sub"

fields="project:,dept:,user:,lfs_prefix:"

hierarchical=  # Not implemented at present
lfs_prefix=/lfs01/workdirs

usage () {
  >&2 echo "Usage: $0 --project= --dept= --user= [--lfs_prefix=]"
}

if ! opts=`getopt -q -o "" -l "help,$fields" -- "$@"`; then
  usage
  exit 1
fi

eval set -- "$opts"

while true; do
  case "$1" in
    --project)
      project="$2"
      shift
      ;;
    --dept)
      dept="$2"
      shift
      ;;
    --user)
      user="$2"
      shift
      ;;
    --lfs_prefix)
      lfs_prefix="$2"
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    --)
      shift
      break
      ;;
  esac
  shift
done

if [ $# -ne 0 ] || \
  [ -z "$project" ] || \
  [ -z "$dept" ] || \
  [ -z "$user" ]; then
  usage
  exit 1
fi

. "$subdir/unix.sh"
. "$subdir/lfs.sh"
. "$subdir/slurm.sh"

# Set PATH if needed (for when invoking via sudo)
for bindir in /opt/pdsh/bin /opt/rocks/{bin,sbin}; do
  echo ":$PATH:" | grep -Fq ":$bindir:" || PATH="$bindir:$PATH"
done

rocks sync users
